costmap_3d:
  ang_resolution: 16
  linear_expand: 0.08
  linear_spread: 0.3
  layers:
    overlay1:
      overlay_mode: max
      linear_expand: 0.15
      linear_spread: 0.3
    overlay2:
      overlay_mode: max
      linear_expand: 0.0
      linear_spread: 0.0
      footprint: [[0.01, -0.01], [0.01, 0.01], [-0.01, 0.01], [-0.01, -0.01]]
